"""initial schema

Revision ID: 844ee30b3918
Revises: 
Create Date: 2025-12-21 22:08:23.656304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844ee30b3918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_generico', sa.String(length=120), nullable=False),
    sa.Column('presentacion', sa.String(length=120), nullable=True),
    sa.Column('forma', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_cedula'), 'patients', ['cedula'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('fecha_consulta', sa.Date(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('notas_medico', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('medicamento_texto', sa.String(length=255), nullable=True),
    sa.Column('dosis', sa.String(length=120), nullable=False),
    sa.Column('horario', sa.String(length=120), nullable=False),
    sa.Column('via', sa.String(length=120), nullable=False),
    sa.Column('duracion', sa.String(length=120), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_catalog.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_medication_id'), 'prescription_items', ['medication_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_visit_id'), 'prescription_items', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_visit_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_medication_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_patients_cedula'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('medication_catalog')
    # ### end Alembic commands ###
